### ISSUE TITLE
not working with electron 13.1.5

### ISSUE THREAD

**Issue by annalenabentele** [snapcrunch/electron-preferences#83]
I just update to latest stable electron version (v13.1.5). Now the preferences are not working any more. 

Using `const preferences = ipcRenderer.sendSync('getPreferences');` in my project throws an exception:

```
Uncaught error occured. Last resort error handler now kicks in
Error: An object could not be cloned.
    at Object.set (electron/js2c/browser_init.js:161:9964)
    at IpcMainImpl.<anonymous> (...\node_modules\electron-preferences\index.js:83:31)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10099)
    at Object.emit (events.js:315:20)
```

**Comment by pvrobays** [comment]
Hi @annalenabentele. Thanks for reporting this issue.
However I'm unable to reproduce this issue.

Reading the error message you've posted I assume that the `preferences` JS object couldn't be cloned. This probably indicates that your preferences object includes some kind of function.
Since the latest electron versions, it's [not possible anymore to send complex objects over IPC](https://www.electronjs.org/docs/breaking-changes#behavior-changed-sending-non-js-objects-over-ipc-now-throws-an-exception).

Could you please share the output of your preferences?

Once we've detected the issue we can decide what the best work around is for your situation, and or if we have to adapt something in the electron-preferences library.

**Comment by pvrobays** [comment]
@annalenabentele Any progress on this issue?
I'm a bit concerned as updating electron broke the library in your situation.

**Comment by annalenabentele** [comment]
Hi @pvrobays , 
thanks a lot for your support. I checked the content of my preferences object once more but it doesn't contain any kind of complex objects. Only strings, bool and int.

If it is only me having this issue and also not reproducible on your side, feel free to close this issue. I'll try to find a solution for my application.

**Comment by pvrobays** [comment]
Hi @annalenabentele 
I'll leave the issue open a little longer. I'm curious what the problem is, and if there's anything we can do at our side to avoid it in the future.

**Comment by lacymorrow** [comment]
@annalenabentele  Could you try with the latest version of electron-preferences and provide the error again?

**Comment by pvrobays** [comment]
Closing this issue due to inactivity. Assuming the original issue has been resolved.
